### PR TITLE
feat: Add a `Cache` API

### LINKED ISSUE #18: Implement a cache to not compile the Wasm module everytime
The idea is basically to add a cache, so that we don't have to validate & compile etc. the whole module everytime. It will improve grately the execution speed.

There is no API in `wasmer-runtime-c-api` yet. I need to work on that. Maybe we will implement that outside the `wasmer-runtime-c-api` crate.

### PR DESCRIPTION
**Pull request by Hywan**
Fix #18.
~Blocked by #25 (this PR contains all its commits).~

This PR adds a `Wasm\Cache` API:

```php
$cache = new Wasm\Cache\Filesystem(CACHE_DIRECTORY);

if ($cache->has(KEY)) {
    $module = $cache->get(KEY);
} else {
    $module = new Wasm\Module(__DIR__ . '/simple.wasm');
    $cache->set(KEY, $module);
}

$instance = $module->instantiate();
$instance->sum(1, 2);
```

The cache API is based on [PSR-16](https://www.php-fig.org/psr/psr-16/).

### CODE REVIEW

**Comment by Hywan** [comment]
Any thoughts on this @xtuc?

**Comment by xtuc** [comment]
Serializing the module to a string seems a bit inefficient to me, and I doubt someone would manipulate the string in PHP. However, manipulating an opaque pointer to the compiled module seems useful. A use-case that comes to my mind is the threading proposal, which requires to instantiate the same compiled Module multiple times.

I'm really not aware of PHP extensions work, but is there a way to keep something in memory for multiple requests? Ideally to me, the opaque pointer would be managed by wasmer.

**Comment by Hywan** [comment]
It is possible to get a persistent data in PHP yes. I don't know how, but I know it is :-).

@nikic Do you think it's a good idea to get a persistent opaque pointer between PHP requests? If yes, any idea how to implement that? Thanks!

**Comment by nikic** [comment]
@Hywan As long as you don't use the per-request allocator, keeping persistent data between request is (on a technical level) not a problem. You need to stick your opaque pointer into globals somewhere and have a mechanism on the PHP side for how it can be accessed again on the next request. (A common example for persistent data are persistent database resources -- but actually using resources is not necessary.)

**Comment by Hywan** [comment]
@nikic Do you know if an extension already does that? Or if Zend offers an API for that? I'm interested by the persistent resource, any documentation? Thanks!

**Comment by Hywan** [comment]
I'll address the persistant module or instance in another issue.

**Pull request merged**
